[package]
name = "aliyun-dysmsapi"
version = "0.1.0"
edition = "2021"
description = "阿里云 Dysmsapi SDK"
license = "MIT OR Apache-2.0"

[dependencies]
aliyun-sdk-core = { path = "../aliyun-sdk-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
